"""Extract the exact-arithmetic skeleton of the perceptron certificates into Lean.

Reads the canonical certificate JSONs of the public proof tree and emits
self-contained Lean 4 files whose kernel-checked theorems restate, over the
integers, the exact-rational claims that the Python verifiers check with
``fractions.Fraction``:

  1. Region I (huang_region1.json): for every band, the serialized Loewner
     majorant packets prove positive definiteness:
         b11_lo > 0,  b22_lo > 0,  b11_lo * b22_lo > max(|b12_lo|,|b12_hi|)^2,
     where packet endpoints are (mid -/+ rad) * 10^exp10.
  2. Region I localization: for every band, the localization leaves grouped by
     (edge, base_segment) form a complete, prefix-free, duplicate-free binary
     cover of depth <= 14  (the verifier's _complete_prefix_tree).
  3. Block 3b/3c replay lanes (b_neg, b_pos, c): every leaf's arb packet
     proves its claimed sign, leaves tile each job interval exactly, and jobs
     tile the lane's schedule boundaries exactly.

Every rational claim is integer-cleared (positive denominators throughout, so
sign and order are preserved).  The Lean side re-decides each claim with the
kernel's bignum arithmetic; no floating point, no Python, no Arb is trusted.

The same extracted data is re-checked here with Fraction arithmetic (the
"mirror") so that an extraction bug cannot silently weaken the Lean claims:
mirror failure aborts generation.

Outputs (under --out):
  Defs header embedded in every generated file (self-contained; no lake).
  R1_BDef_XX.lean, R1_Cover_XX.lean, B3bc_signs.lean, and manifest.json
  binding input and output SHA-256 hashes.

This is deliberately NOT a formalization of the analytic mathematics (Gaussian
integrals, entropy duality, ray concavity).  It kernel-checks the exact
combinatorial/algebraic layer of the certificate chain in a second, foreign
proof system.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from fractions import Fraction

CHUNK_BANDS = 200          # bands per generated Lean file

DEFS = r'''-- Auto-generated by extract_skeleton.py; self-contained (no imports).
-- Exact-arithmetic skeleton checks, kernel-decided over Int/Nat.
set_option maxHeartbeats 4000000
set_option maxRecDepth 8192

def pathOfString (s : String) : List Bool := s.toList.map (fun c => c == '1')

def coverAux (paths : List (List Bool)) (fuel : Nat) (pre : List Bool) : Bool :=
  if paths.any (fun p => p == pre) then
    paths.all (fun p => p == pre || !(pre.isPrefixOf p))
  else
    match fuel with
    | 0 => false
    | Nat.succ f => coverAux paths f (pre ++ [false]) && coverAux paths f (pre ++ [true])

/-- Complete, prefix-free, duplicate-free binary leaf cover of depth <= `depth`. -/
def coverOk (paths : List String) (depth : Nat) : Bool :=
  let ps := paths.map pathOfString
  ps.eraseDups.length == ps.length && coverAux ps depth []

/-- All 32 localization groups of one band cover their trees (depth 14). -/
def bandCoverOk (groups : List (List String)) : Bool :=
  groups.length == 32 && groups.all (fun g => coverOk g 14)

/-- Loewner-majorant definiteness from packet endpoints.
    Data: (m11, r11, m22, r22, m12, r12, sh1, sh2) with
    sh1 = e11+e22-s, sh2 = 2*e12-s, s = min(e11+e22, 2*e12).  Claims:
    m11-r11 > 0, m22-r22 > 0, and
    (m11-r11)(m22-r22)*10^sh1 > max(|m12-r12|,|m12+r12|)^2*10^sh2. -/
def bDefOk : Int × Int × Int × Int × Int × Int × Nat × Nat → Bool
  | (m11, r11, m22, r22, m12, r12, sh1, sh2) =>
    let l11 := m11 - r11
    let l22 := m22 - r22
    let b := (max (m12 - r12).natAbs (m12 + r12).natAbs : Int)
    decide (0 < l11) && decide (0 < l22) &&
    decide (b * b * (10:Int) ^ sh2 < l11 * l22 * (10:Int) ^ sh1)

/-- One certified sign leaf: interval [nLo/dLo, nHi/dHi] (dLo,dHi > 0),
    packet (mid, rad), claimed sign s (true = ">0", false = "<0").
    Claims: interval nonempty, and mid-rad > 0 (resp. mid+rad < 0). -/
def leafOk : Int × Int × Int × Int × Int × Int × Bool → Bool
  | (nLo, dLo, nHi, dHi, mid, rad, s) =>
    decide (0 < dLo) && decide (0 < dHi) && decide (nLo * dHi < nHi * dLo) &&
    (if s then decide (0 < mid - rad) else decide (mid + rad < 0))

/-- Exact rational equality by cross-multiplication (positive denominators). -/
def fracEq : Int × Int × Int × Int → Bool
  | (a, b, c, d) => decide (0 < b) && decide (0 < d) && decide (a * d = c * b)

def allB (xs : List (Int × Int × Int × Int × Int × Int × Nat × Nat)) : Bool :=
  xs.all bDefOk

def allLeaves (xs : List (Int × Int × Int × Int × Int × Int × Bool)) : Bool :=
  xs.all leafOk

def allEq (xs : List (Int × Int × Int × Int)) : Bool :=
  xs.all fracEq

def allCovers (xs : List (List (List String))) : Bool :=
  xs.all bandCoverOk

/-- Strict rational order a/b < c/d with positive denominators. -/
def fracLt : Int × Int × Int × Int → Bool
  | (a, b, c, d) => decide (0 < b) && decide (0 < d) && decide (a * d < c * b)

/-- Weak rational order a/b <= c/d with positive denominators. -/
def fracLe : Int × Int × Int × Int → Bool
  | (a, b, c, d) => decide (0 < b) && decide (0 < d) && decide (a * d <= c * b)

def allLe (xs : List (Int × Int × Int × Int)) : Bool :=
  xs.all fracLe

/-- Arb packet proves strict negativity: mid + rad < 0. -/
def negPacket : Int × Int → Bool
  | (mid, rad) => decide (0 <= rad) && decide (mid + rad < 0)

/-- Arb packet proves strict positivity: mid - rad > 0. -/
def posPacket : Int × Int → Bool
  | (mid, rad) => decide (0 <= rad) && decide (0 < mid - rad)

def allLt (xs : List (Int × Int × Int × Int)) : Bool :=
  xs.all fracLt

def allNeg (xs : List (Int × Int)) : Bool :=
  xs.all negPacket

def allPos (xs : List (Int × Int)) : Bool :=
  xs.all posPacket
'''


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for block in iter(lambda: f.read(1 << 20), b''):
            h.update(block)
    return h.hexdigest()


def canonical_int(text) -> int:
    if isinstance(text, int) and not isinstance(text, bool):
        return text
    if not isinstance(text, str):
        raise ValueError(f'integer literal must be str or int: {text!r}')
    value = int(text)
    if str(value) != text:
        raise ValueError(f'non-canonical integer literal: {text!r}')
    return value


def frac(record) -> Fraction:
    if not isinstance(record, dict) or set(record) != {'num', 'den'}:
        raise ValueError('invalid rational record schema')
    num = canonical_int(record['num'])
    den = canonical_int(record['den'])
    if den <= 0:
        raise ValueError('rational denominator must be positive')
    out = Fraction(num, den)
    if (out.numerator, out.denominator) != (num, den):
        raise ValueError('rational record is not reduced/canonical')
    return out


def packet(record):
    required = {'format', 'mid10', 'rad10', 'exp10', 'digits'}
    if not isinstance(record, dict) or set(record) != required:
        raise ValueError('invalid Arb packet schema')
    if record['format'] != 'arb-midrad10-v1':
        raise ValueError('unknown Arb packet format')
    mid = canonical_int(record['mid10'])
    rad = canonical_int(record['rad10'])
    if rad < 0:
        raise ValueError('negative packet radius')
    exp10 = record['exp10']
    if not isinstance(exp10, int) or isinstance(exp10, bool):
        raise ValueError('packet exponent must be a plain integer')
    return mid, rad, exp10


def packet_endpoints(record):
    mid, rad, exp10 = packet(record)
    scale = Fraction(10 ** exp10) if exp10 >= 0 else Fraction(1, 10 ** -exp10)
    return (mid - rad) * scale, (mid + rad) * scale


def lean_int(v: int) -> str:
    return f'({v})' if v < 0 else str(v)


def extract_region1(path):
    data = json.load(open(path))
    records = data['records']
    if len(records) != 1404:
        raise ValueError(f'expected 1404 Region-I records, got {len(records)}')
    b_rows, cover_rows = [], []
    mirror_leaves = 0
    for rec in records:
        if rec.get('verdict') != 'PASS' or rec.get('failure') is not None:
            raise ValueError(f'non-PASS record {rec.get("index")}')
        cert = rec['B_certificate']
        m11, r11, e11 = packet(cert['b11_packet'])
        m12, r12, e12 = packet(cert['b12_packet'])
        m22, r22, e22 = packet(cert['b22_packet'])
        p, q = e11 + e22, 2 * e12
        s = min(p, q)
        sh1, sh2 = p - s, q - s
        # mirror check with Fractions (the verifier's own inequality)
        b11lo, _ = packet_endpoints(cert['b11_packet'])
        b12lo, b12hi = packet_endpoints(cert['b12_packet'])
        b22lo, _ = packet_endpoints(cert['b22_packet'])
        if not (b11lo > 0 and b22lo > 0
                and b11lo * b22lo - max(abs(b12lo), abs(b12hi)) ** 2 > 0):
            raise ValueError(f'mirror: band {rec["index"]} packets not definite')
        b_rows.append((m11, r11, m22, r22, m12, r12, sh1, sh2))

        loc = rec['localization_certificate']
        if loc['initial_segments_per_edge'] != 8 or loc['max_depth'] != 14:
            raise ValueError('unexpected localization geometry')
        groups = {(e, b): [] for e in range(4) for b in range(8)}
        seen = set()
        for leaf in loc['leaves']:
            edge, base = leaf['edge'], leaf['base_segment']
            if (isinstance(edge, bool) or isinstance(base, bool)
                    or not isinstance(edge, int) or not isinstance(base, int)):
                raise ValueError('localization edge/base must be plain ints')
            key = (edge, base, leaf['path'])
            if key in seen:
                raise ValueError('duplicate localization leaf')
            seen.add(key)
            path_str = leaf['path']
            if not isinstance(path_str, str) or set(path_str) - {'0', '1'}:
                raise ValueError('invalid leaf path')
            groups[(leaf['edge'], leaf['base_segment'])].append(path_str)
            for cert in leaf['polygon_certificates']:
                weights = [frac(w) for w in cert['weights']]
                if (len(weights) != len(loc['fan'])
                        or any(w < 0 for w in weights)
                        or sum(weights, Fraction(0)) != 1):
                    raise ValueError('mirror: invalid localization convex weights')
        mirror_complete_cover(groups)
        mirror_leaves += len(loc['leaves'])
        ordered = [groups[(e, b)] for e in range(4) for b in range(8)]
        cover_rows.append(ordered)
    return b_rows, cover_rows, mirror_leaves, data['certificate_sha256']


def extract_region1_trees(path):
    """Angular split partitions, outside-star radius facts, radial chains,
    curvature negativity, and tilt/qB positivity from the Region-I trees."""
    data = json.load(open(path))
    eq_rows, lt_rows, le_rows, neg_rows, pos_rows = [], [], [], [], []
    counts = {'splits': 0, 'outside': 0, 'certified': 0, 'pieces': 0}

    def eq(a, b):
        eq_rows.append((a.numerator, a.denominator, b.numerator, b.denominator))

    def lt(a, b):
        if not a < b:
            raise ValueError('mirror: ordering row violated')
        lt_rows.append((a.numerator, a.denominator, b.numerator, b.denominator))

    def le(a, b):
        if not a <= b:
            raise ValueError('mirror: weak ordering row violated')
        le_rows.append((a.numerator, a.denominator, b.numerator, b.denominator))

    def walk(node, lo, hi, t0, t1):
        if frac(node['theta_lo']) != lo or frac(node['theta_hi']) != hi:
            raise ValueError('mirror: angular geometry mismatch')
        eq(frac(node['theta_lo']), lo)
        eq(frac(node['theta_hi']), hi)
        kind = node['kind']
        if kind == 'split':
            counts['splits'] += 1
            mid = frac(node['split_at'])
            lt(lo, mid)
            lt(mid, hi)
            walk(node['children'][0], lo, mid, t0, t1)
            walk(node['children'][1], mid, hi, t0, t1)
            return
        if kind == 'outside_star':
            counts['outside'] += 1
            le(frac(node['tmax']), t0)
            return
        if kind != 'certified':
            raise ValueError(f'mirror: unknown angular node kind {kind!r}')
        counts['certified'] += 1
        tmax = frac(node['tmax'])
        end = frac(node['radial_end'])
        if end != min(t1, tmax):
            raise ValueError('mirror: radial_end is not min(t1, tmax)')
        le(end, t1)
        le(end, tmax)
        lt(t0, end)
        mid, rad, _ = packet(node['qB_packet'])
        plo, _ = packet_endpoints(node['qB_packet'])
        if not plo > 0:
            raise ValueError('mirror: qB packet not positive')
        pos_rows.append((mid, rad))
        reach = t0
        for piece in node['radial_pieces']:
            counts['pieces'] += 1
            left = frac(piece['radius_lo'])
            right = frac(piece['radius_hi'])
            if left != reach:
                raise ValueError('mirror: radial chain gap')
            eq(left, reach)
            lt(left, right)
            mid, rad, _ = packet(piece['curvature_packet'])
            _, phi = packet_endpoints(piece['curvature_packet'])
            if not phi < 0:
                raise ValueError('mirror: curvature packet not negative')
            neg_rows.append((mid, rad))
            mid, rad, _ = packet(piece['s_box'])
            slo, _ = packet_endpoints(piece['s_box'])
            if not slo > 0:
                raise ValueError('mirror: tilt packet not positive')
            pos_rows.append((mid, rad))
            reach = right
        if reach != end:
            raise ValueError('mirror: radial chain stops short')
        eq(reach, end)

    for rec in data['records']:
        t0, t1, th0, th1 = (frac(v) for v in rec['geometry'])
        for root in rec['angular_roots']:
            walk(root, frac(root['theta_lo']), frac(root['theta_hi']), t0, t1)
            # roots span the band's angular interval jointly; bind endpoints
        roots = rec['angular_roots']
        eq(frac(roots[0]['theta_lo']), th0)
        eq(frac(roots[-1]['theta_hi']), th1)
        for first, second in zip(roots, roots[1:]):
            eq(frac(first['theta_hi']), frac(second['theta_lo']))
    return eq_rows, lt_rows, le_rows, neg_rows, pos_rows, counts


def mirror_complete_cover(groups):
    for paths in groups.values():
        pathset = set(paths)
        if len(pathset) != len(paths) or not pathset:
            raise ValueError('mirror: duplicate/empty cover group')

        def visit(prefix):
            if prefix in pathset:
                if any(o != prefix and o.startswith(prefix) for o in pathset):
                    raise ValueError('mirror: overlapping leaves')
                return
            if len(prefix) >= 14:
                raise ValueError('mirror: cover gap')
            visit(prefix + '0')
            visit(prefix + '1')

        visit('')


def extract_b3bc(replay_dir):
    leaf_rows, eq_rows, lane_summaries = [], [], []
    for part in ('b_neg', 'b_pos', 'c'):
        lane_path = os.path.join(replay_dir, f'{part}.lane-0-of-1.json')
        lane = json.load(open(lane_path))
        if lane['failures'] != 0 or lane['part'] != part:
            raise ValueError(f'lane {part} not clean')
        bounds = [frac(b) for b in lane['schedule_boundaries']]
        records = lane['records']
        if len(records) != len(bounds) - 1:
            raise ValueError(f'lane {part}: records/boundaries mismatch')
        if any(bounds[i] >= bounds[i + 1] for i in range(len(bounds) - 1)):
            raise ValueError(f'lane {part}: boundaries not increasing')
        n_leaves = 0
        for i, rec in enumerate(records):
            if rec['failure'] is not None or rec.get('ok') is not True:
                raise ValueError(f'lane {part} job {i} failed')
            job_lo, job_hi = frac(rec['tau_lo']), frac(rec['tau_hi'])
            if (job_lo, job_hi) != (bounds[i], bounds[i + 1]):
                raise ValueError(f'lane {part} job {i} escapes schedule')
            eq_rows.append((job_lo.numerator, job_lo.denominator,
                            bounds[i].numerator, bounds[i].denominator))
            eq_rows.append((job_hi.numerator, job_hi.denominator,
                            bounds[i + 1].numerator, bounds[i + 1].denominator))
            leaves = rec['leaves']
            if not leaves:
                raise ValueError(f'lane {part} job {i} has no leaves')
            reach = job_lo
            for leaf in leaves:
                lo, hi = frac(leaf['tau_lo']), frac(leaf['tau_hi'])
                if lo != reach:
                    raise ValueError(f'lane {part} job {i}: leaf tiling gap')
                if not lo < hi:
                    raise ValueError(f'lane {part} job {i}: empty leaf')
                eq_rows.append((lo.numerator, lo.denominator,
                                reach.numerator, reach.denominator))
                sign = leaf['sign']
                if sign not in ('>0', '<0'):
                    raise ValueError(f'unknown sign claim {sign!r}')
                mid, rad, _ = packet(leaf['value'])
                plo, phi = packet_endpoints(leaf['value'])
                if sign == '>0' and not plo > 0:
                    raise ValueError(f'mirror: lane {part} job {i} sign not proven')
                if sign == '<0' and not phi < 0:
                    raise ValueError(f'mirror: lane {part} job {i} sign not proven')
                leaf_rows.append((lo.numerator, lo.denominator,
                                  hi.numerator, hi.denominator,
                                  mid, rad, sign == '>0'))
                reach = hi
                n_leaves += 1
            if reach != job_hi:
                raise ValueError(f'lane {part} job {i}: leaves stop short')
        lane_summaries.append({
            'part': part, 'jobs': len(records), 'leaves': n_leaves,
            'span': [str(bounds[0]), str(bounds[-1])],
            'artifact_sha256': lane.get('artifact_sha256'),
        })
    return leaf_rows, eq_rows, lane_summaries


def decimal_fraction(text) -> Fraction:
    """Exact rational from a plain decimal string like "-0.241"."""
    if not isinstance(text, str) or not text:
        raise ValueError(f'decimal literal must be a nonempty string: {text!r}')
    sign = -1 if text.startswith('-') else 1
    body = text.lstrip('+-')
    if '.' in body:
        whole, frac_part = body.split('.', 1)
        if not (whole + frac_part).isdigit() or not frac_part:
            raise ValueError(f'invalid decimal literal: {text!r}')
        return sign * Fraction(int(whole + frac_part), 10 ** len(frac_part))
    if not body.isdigit():
        raise ValueError(f'invalid decimal literal: {text!r}')
    return sign * Fraction(int(body))


def extract_block3a(results_dir):
    cert = json.load(open(os.path.join(results_dir, 'block3a_certificate.json')))
    rows = []
    raw = open(os.path.join(results_dir, 'run_root', 'block3a.jsonl'),
               'rb').read()
    for line in raw[:-1].split(b'\n'):
        rows.append(json.loads(line.decode('utf-8')))
    if len(rows) != cert['coverage']['cells']:
        raise ValueError('block3a row count differs from certificate coverage')
    neg_rows, eq_rows = [], []
    total_leaves = 0
    max_upper = None
    cells = []
    for row in rows:
        if row['verdict'] != 'PASS':
            raise ValueError(f'block3a row {row["index"]} not PASS')
        if (row['recursive_calls'] + 1) // 2 != len(row['leaf_bounds']):
            raise ValueError(f'block3a row {row["index"]} recursion mismatch')
        lo, hi = decimal_fraction(row['tau_lo']), decimal_fraction(row['tau_hi'])
        if not lo < hi:
            raise ValueError(f'block3a row {row["index"]} empty cell')
        cells.append((lo, hi, row['kind']))
        for pkt in row['leaf_bounds']:
            mid, rad, _ = packet(pkt)
            plo, phi = packet_endpoints(pkt)
            if not phi < 0:
                raise ValueError(f'mirror: block3a row {row["index"]} leaf not negative')
            max_upper = phi if max_upper is None else max(max_upper, phi)
            neg_rows.append((mid, rad))
            total_leaves += 1
    if total_leaves != cert['coverage']['total_recursive_leaves']:
        raise ValueError('block3a leaf count differs from certificate coverage')
    if max_upper != frac(cert['coverage']['max_leaf_upper']):
        raise ValueError('block3a max_leaf_upper differs from certificate')
    # tiling: sort cells, chain within contiguous runs
    cells.sort(key=lambda c: (c[0], c[1]))
    runs = []
    for lo, hi, kind in cells:
        if runs and runs[-1][1] == lo:
            eq_rows.append((lo.numerator, lo.denominator,
                            runs[-1][1].numerator, runs[-1][1].denominator))
            runs[-1][1] = hi
        elif runs and runs[-1][1] > lo:
            raise ValueError('block3a cells overlap')
        else:
            runs.append([lo, hi])
    run_spans = [[str(a), str(b)] for a, b in runs]
    return neg_rows, eq_rows, run_spans, total_leaves, cert['certificate_sha256']


def extract_sweeps(results_dir):
    """Flatten both sweep stages: split-partition equalities/orders and
    negative-leaf packets, with counts mirrored against derived_summary."""
    eq_rows, lt_rows, neg_rows, le_rows = [], [], [], []
    summaries = []
    stage_delegates = {}
    for stage, name in ((1, 'huang_sweep.json'), (2, 'huang_sweep2.json')):
        data = json.load(open(os.path.join(results_dir, name)))
        counts = {'negative': 0, 'outside_K': 0, 'delegate': 0, 'split': 0}
        delegates = stage_delegates.setdefault(stage, [])

        def walk(node, rect):
            kind = node['kind']
            cell = [frac(v) for v in node['cell']]
            if tuple(cell) != tuple(rect):
                raise ValueError('mirror: sweep node geometry mismatch')
            if kind == 'split':
                counts['split'] += 1
                axis = node['axis']
                split = frac(node['split_at'])
                lower, upper = (rect[0], rect[1]) if axis == 1 else (rect[2], rect[3])
                if not lower < split < upper:
                    raise ValueError('mirror: sweep split outside cell')
                lt_rows.append((lower.numerator, lower.denominator,
                                split.numerator, split.denominator))
                lt_rows.append((split.numerator, split.denominator,
                                upper.numerator, upper.denominator))
                if axis == 1:
                    child0 = (rect[0], split, rect[2], rect[3])
                    child1 = (split, rect[1], rect[2], rect[3])
                else:
                    child0 = (rect[0], rect[1], rect[2], split)
                    child1 = (rect[0], rect[1], split, rect[3])
                for child, crect in zip(node['children'], (child0, child1)):
                    ccell = [frac(v) for v in child['cell']]
                    for mine, theirs in zip(crect, ccell):
                        eq_rows.append((mine.numerator, mine.denominator,
                                        theirs.numerator, theirs.denominator))
                    walk(child, crect)
            elif kind == 'negative':
                counts['negative'] += 1
                mid, rad, _ = packet(node['value_packet'])
                plo, phi = packet_endpoints(node['value_packet'])
                if not phi < 0:
                    raise ValueError('mirror: sweep negative leaf not negative')
                neg_rows.append((mid, rad))
            elif kind == 'outside_K':
                counts['outside_K'] += 1
            elif kind in ('delegate_sweep2', 'delegate_region1'):
                counts['delegate'] += 1
                delegates.append(cell)
            else:
                raise ValueError(f'mirror: unknown sweep node kind {kind!r}')

        for record in data['records']:
            if record['verdict'] != 'PASS':
                raise ValueError('sweep record not PASS')
            rect = tuple(frac(v) for v in record['cell'])
            walk(record['tree'], rect)
        summary = data['derived_summary']
        for key, want in (('negative_leaves', counts['negative']),
                          ('outside_leaves', counts['outside_K']),
                          ('delegated_leaves', counts['delegate'])):
            if key in summary and summary[key] != want:
                raise ValueError(
                    f'sweep stage {stage} {key}: walked {want} vs summary {summary[key]}')
        summaries.append({'stage': stage, 'counts': counts,
                          'derived_summary': summary,
                          'certificate_sha256': data['certificate_sha256']})
        if stage == 1:
            a1max = frac(data['policy']['A1MAX'])
            a2max = frac(data['policy']['A2MAX'])
            stage1_domain = (-a1max, a1max, -a2max, a2max)
            stage1_roots = [tuple(frac(v) for v in rec['cell'])
                            for rec in data['records']]
        else:
            excl_old = tuple(frac(v) for v in data['policy']['EXCL_OLD'])
            stage2_roots = [tuple(frac(v) for v in rec['cell'])
                            for rec in data['records']]

    def contain(rect, dom):
        for mine, bound, flip in ((rect[0], dom[0], True),
                                  (rect[1], dom[1], False),
                                  (rect[2], dom[2], True),
                                  (rect[3], dom[3], False)):
            lo, hi = (bound, mine) if flip else (mine, bound)
            if not lo <= hi:
                raise ValueError('mirror: containment row violated')
            le_rows.append((lo.numerator, lo.denominator,
                            hi.numerator, hi.denominator))

    for rect in stage1_roots:
        contain(rect, stage1_domain)
    for rect in stage2_roots:
        contain(rect, excl_old)
    for rect in stage_delegates[1]:
        contain(rect, excl_old)
    return eq_rows, lt_rows, neg_rows, le_rows, summaries


def write_lean(path, body):
    with open(path, 'w', newline='\n', encoding='utf-8') as f:
        f.write(DEFS)
        f.write(body)
    return sha256_file(path)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--results', required=True)
    ap.add_argument('--out', required=True)
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)

    r1_path = os.path.join(args.results, 'huang_region1.json')
    b_rows, cover_rows, loc_leaves, r1_sha = extract_region1(r1_path)
    leaf_rows, eq_rows, lanes = extract_b3bc(
        os.path.join(args.results, 'block3bc_replay'))
    b3a_neg, b3a_eq, b3a_runs, b3a_leaves, b3a_sha = extract_block3a(
        args.results)
    sw_eq, sw_lt, sw_neg, sw_le, sw_summaries = extract_sweeps(args.results)

    outputs = {}

    def emit_chunked(prefix, rows, lean_type, render, checker, size=200):
        for c in range((len(rows) + size - 1) // size):
            chunk = rows[c * size:(c + 1) * size]
            items = ',\n  '.join(render(row) for row in chunk)
            body = (f'\ndef {prefix}Data{c} : List ({lean_type}) := [\n  '
                    + items + ']\n\n'
                    f'theorem {prefix}_chunk{c} : {checker} {prefix}Data{c} '
                    '= true := by decide\n')
            name = f'{prefix}_{c:02d}.lean'
            outputs[name] = write_lean(os.path.join(args.out, name), body)

    def render_pair(row):
        return '(' + ', '.join(lean_int(v) for v in row) + ')'

    emit_chunked('B3a_neg', b3a_neg, 'Int × Int', render_pair, 'allNeg')
    emit_chunked('B3a_tile', b3a_eq, 'Int × Int × Int × Int', render_pair,
                 'allEq')
    emit_chunked('Sweep_eq', sw_eq, 'Int × Int × Int × Int', render_pair,
                 'allEq')
    emit_chunked('Sweep_lt', sw_lt, 'Int × Int × Int × Int', render_pair,
                 'allLt')
    emit_chunked('Sweep_neg', sw_neg, 'Int × Int', render_pair, 'allNeg')
    emit_chunked('Sweep_contain', sw_le, 'Int × Int × Int × Int', render_pair,
                 'allLe')
    r1t_eq, r1t_lt, r1t_le, r1t_neg, r1t_pos, r1t_counts = \
        extract_region1_trees(r1_path)
    emit_chunked('R1T_eq', r1t_eq, 'Int × Int × Int × Int', render_pair,
                 'allEq', size=600)
    emit_chunked('R1T_lt', r1t_lt, 'Int × Int × Int × Int', render_pair,
                 'allLt', size=600)
    emit_chunked('R1T_le', r1t_le, 'Int × Int × Int × Int', render_pair,
                 'allLe', size=600)
    emit_chunked('R1T_curv', r1t_neg, 'Int × Int', render_pair, 'allNeg',
                 size=400)
    emit_chunked('R1T_pos', r1t_pos, 'Int × Int', render_pair, 'allPos',
                 size=400)
    n_chunks = (len(b_rows) + CHUNK_BANDS - 1) // CHUNK_BANDS
    for c in range(n_chunks):
        rows = b_rows[c * CHUNK_BANDS:(c + 1) * CHUNK_BANDS]
        items = ',\n  '.join(
            '(' + ', '.join(
                [lean_int(v) for v in row[:6]] + [str(row[6]), str(row[7])]
            ) + ')' for row in rows)
        body = (f'\ndef bDefData{c} : '
                'List (Int × Int × Int × Int × Int × Int × Nat × Nat) := [\n  '
                + items + ']\n\n'
                f'theorem region1_bdef_chunk{c} : allB bDefData{c} = true := by decide\n')
        name = f'R1_BDef_{c:02d}.lean'
        outputs[name] = write_lean(os.path.join(args.out, name), body)

    for c in range(n_chunks):
        rows = cover_rows[c * CHUNK_BANDS:(c + 1) * CHUNK_BANDS]
        bands = ',\n  '.join(
            '[' + ', '.join(
                '[' + ', '.join(json.dumps(p) for p in group) + ']'
                for group in band) + ']'
            for band in rows)
        body = (f'\ndef coverData{c} : List (List (List String)) := [\n  '
                + bands + ']\n\n'
                f'theorem region1_cover_chunk{c} : allCovers coverData{c} = true := by decide\n')
        name = f'R1_Cover_{c:02d}.lean'
        outputs[name] = write_lean(os.path.join(args.out, name), body)

    body_parts = []
    n_leaf_chunks = (len(leaf_rows) + 199) // 200
    for c in range(n_leaf_chunks):
        rows = leaf_rows[c * 200:(c + 1) * 200]
        items = ',\n  '.join(
            '(' + ', '.join([lean_int(v) for v in row[:6]]
                            + ['true' if row[6] else 'false']) + ')'
            for row in rows)
        body_parts.append(
            f'\ndef b3bcLeaves{c} : '
            'List (Int × Int × Int × Int × Int × Int × Bool) := [\n  '
            + items + ']\n\n'
            f'theorem b3bc_signs_chunk{c} : allLeaves b3bcLeaves{c} = true := by decide\n')
    n_eq_chunks = (len(eq_rows) + 199) // 200
    for c in range(n_eq_chunks):
        rows = eq_rows[c * 200:(c + 1) * 200]
        items = ',\n  '.join(
            '(' + ', '.join(lean_int(v) for v in row) + ')' for row in rows)
        body_parts.append(
            f'\ndef b3bcTiling{c} : List (Int × Int × Int × Int) := [\n  '
            + items + ']\n\n'
            f'theorem b3bc_tiling_chunk{c} : allEq b3bcTiling{c} = true := by decide\n')
    outputs['B3bc_signs.lean'] = write_lean(
        os.path.join(args.out, 'B3bc_signs.lean'), ''.join(body_parts))

    manifest = {
        'kind': 'lean_skeleton_manifest',
        'inputs': {
            'huang_region1.json': sha256_file(r1_path),
            'huang_region1.certificate_sha256': r1_sha,
            'block3bc_replay_lanes': lanes,
            'block3a.certificate_sha256': b3a_sha,
            'block3a_tau_runs': b3a_runs,
            'sweep_stages': sw_summaries,
        },
        'counts': {
            'region1_bands': len(b_rows),
            'region1_localization_leaves': loc_leaves,
            'b3bc_sign_leaves': len(leaf_rows),
            'b3bc_tiling_equalities': len(eq_rows),
            'block3a_negative_leaves': len(b3a_neg),
            'block3a_tiling_equalities': len(b3a_eq),
            'sweep_partition_equalities': len(sw_eq),
            'sweep_split_orderings': len(sw_lt),
            'sweep_negative_leaves': len(sw_neg),
            'sweep_containment_rows': len(sw_le),
            'region1_tree_counts': r1t_counts,
            'region1_tree_rows': {
                'eq': len(r1t_eq), 'lt': len(r1t_lt), 'le': len(r1t_le),
                'curvature_neg': len(r1t_neg), 'pos': len(r1t_pos)},
        },
        'outputs': outputs,
        'defs_sha256': hashlib.sha256(DEFS.encode()).hexdigest(),
    }
    with open(os.path.join(args.out, 'manifest.json'), 'w', newline='\n',
              encoding='utf-8') as f:
        json.dump(manifest, f, indent=1, sort_keys=True)
    print(json.dumps(manifest['counts'], indent=1))
    print('files:', len(outputs))


if __name__ == '__main__':
    main()
